version: '3.8'

services:
  nsc:
    build: .
    container_name: nsc
    privileged: true
    devices:
      - /dev/gpiochip0:/dev/gpiochip0
      - /dev/gpiochip1:/dev/gpiochip1
      - /dev/gpiochip2:/dev/gpiochip2
      - /dev/gpiochip3:/dev/gpiochip3
      - /dev/gpiochip4:/dev/gpiochip4
      - /dev/gpiochip5:/dev/gpiochip5
    ports:
      - "${REST_PORT}:${REST_PORT}"
    env_file:
      - .env
    restart: unless-stopped
